wordpress:
  build: .
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
    - ../delibera:/var/www/html/wp-content/plugins/delibera
    - .:/var/www/html/wp-content/themes/mapasculturais
    - ./.data/wp:/var/www/html/
    - ./.data/php:/usr/local/php/conf.d

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
  volumes:
    - "./.data/db:/var/lib/mysql"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  ports:
    - 3000:80
